// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)
